// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqlxboeipgunsgwifiln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxbHhib2VpcGd1bnNnd2lmaWxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MDQyMTMsImV4cCI6MjA2MzI4MDIxM30.YQkEaL8cJVrqIBT1tYlQmCG_grH0EXmyQ9XM1M-DtME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);